jobs:
  validate:
    image: node:12
    requires: [ ~pr, ~commit ]
    steps:
      - install: npm i -g screwdriver-template-main
      - validate_default_template: template-validate
      - validate_nodejs_template: |
          export SD_TEMPLATE_PATH=./sd-template.yaml
          template-validate
      - install_prerequisites: npm install -g screwdriver-template-main
      - publish:  template-publish
