jobs:
  validate:
    image: buildpack-deps
    requires: [ ~pr ]
    steps:
      - install: npm i -g screwdriver-template-main
      - validate: template-validate
  publish:
    requires: [ ~commit ]
    template: screwdriver/template-publish@stable
