shared:
  annotations:
    screwdriver.cd/timeout: 2880
  requires: [ ~commit, ~pr ]
  image: buildpack-deps
jobs:
   run_test:
    steps:
            - git clone https://shmastuura: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@github.com/shmatsuura/sd-test.git
            - cd sd-test;ls
            - echo "aaa" >>test.csv
            - git add . ; git commit -m "test"
