shared:
  annotations:
    screwdriver.cd/timeout: 2880
  requires: [ ~commit, ~pr ]
  image: buildpack-deps
  environment: 
   ACCESS_TOKEN: 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
jobs:
   run_test:
    steps:
            - git config --global credential.helper store
            - git config --global user.name "shmatsuura"
            - git clone https://shmastuura:${ACCESS_TOKEN}@github.com/shmatsuura/sd-test.git
            - git config --global credential.helper store
            - git config --global user.name "shmatsuura"
            - cd sd-test;ls
            - echo "aaa" >>test.csv
            - git add . ; git commit -m "test"
            - git push -u origin main
